spring.application.name=Employeedata
server.port=9090
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=EmployeeData
#spring.data.mongodb.username=myemployee
#spring.data.mongodb.password=mypassword



